[package]
name = "topgg"
version = "2.0.0"
edition = "2024"
rust-version = "1.87"
authors = ["null (https://github.com/null8626)", "Top.gg <support@top.gg> (https://top.gg)"]
description = "The community-maintained Rust SDK for Top.gg."
readme = "README.md"
repository = "https://github.com/Top-gg-Community/rust-sdk"
license = "MIT"
keywords = ["discord", "bot", "topgg"]
categories = ["api-bindings", "web-programming::http-client"]
exclude = [".gitattributes", ".github/", ".gitignore", "rustfmt.toml"]

[dependencies]
cfg-if = "1"
reqwest = { version = "0.12", optional = true }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "sync", "time"], optional = true }
urlencoding = { version = "2", optional = true }
bytes = { version = "1.11", optional = true }
hex = { version = "0.4", optional = true }
sha2 = { version = "0.10", optional = true }
hmac = { version = "0.12", optional = true }
futures-core = { version = "0.3", optional = true }

serenity = { version = "0.12", features = ["builder", "client", "gateway", "model", "utils"], optional = true }

twilight-http = { version = "0.15", optional = true }
twilight-model = { version = "0.15", optional = true }

chrono = { version = "0.4", default-features = false, features = ["serde", "now"] }
serde_json = "1"
serde_variant = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }

rocket = { version = "0.5", default-features = false, features = ["json"], optional = true }
axum = { version = "0.8", default-features = false, optional = true, features = ["http1", "tokio"] }
async-trait = { version = "0.1", optional = true }
warp = { version = "0.3", default-features = false, optional = true }
actix-web = { version = "4", default-features = false, optional = true }
tower = { version = "0.5", features = ["timeout"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
twilight-gateway = "0.15"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
rustc-args = ["--cfg", "docsrs"]

[features]
default = ["api"]
api = ["async-trait", "reqwest", "serde_variant", "urlencoding"]

serenity = ["dep:serenity"]
twilight = ["twilight-http", "twilight-model"]

webhooks = ["hex", "hmac", "log", "sha2"]
rocket = ["webhooks", "tokio/time", "dep:rocket"]
axum = ["webhooks", "async-trait", "tower", "dep:axum"]
warp = ["webhooks", "bytes", "dep:warp"]
actix-web = ["webhooks", "futures-core", "dep:actix-web"]

[lints.rust]
unsafe_code = "forbid"

[lints.rustdoc]
broken_intra_doc_links = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
