[package]
name = "top-gg"
version = "0.1.0"
authors = ["14ROVI <29734170+14ROVI@users.noreply.github.com>"]
categories = ["top-gg", "sdk", "asynchronous", "api-bindings"]
keywords = ["top-gg"]
license = "MIT"
description = "Top.gg API client"
edition = "2018"
readme = "README.md"
repository = "https://github.com/top-gg/rust-sdk.git"


[lib]
name = "topgg"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }