[package]
name = "topgg-rs"
version = "0.1.0"
authors = ["14ROVI <29734170+14ROVI@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/14ROVI/topgg-rs"
readme = "README.md"
description = "A top.gg library that makes posting and getting info easy!"
keywords = ["discord", "bots", "topgg", "dbl", "discordbotslist"]
categories = ["api-bindings", "web-programming::http-client"]
license = "MIT"


[lib]
name = "topgg"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }